


UPDATE SHARES set REMOVABLE = 1;

ALTER TABLE "APP"."QUOTATIONS" DROP PRIMARY KEY;
ALTER TABLE QUOTATIONS ADD COLUMN "ORIGIN" SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE "APP"."QUOTATIONS" ADD CONSTRAINT "QUOTATIONS_SYMBOL_ISIN_DATE_ORIGIN" PRIMARY KEY ("SYMBOL", "ISIN", "DATE", "ORIGIN");
CREATE INDEX "STOCK_DATE_ORIGIN" on "QUOTATIONS" ("SYMBOL", "ISIN", "DATE");

