ALTER TABLE SHARES ALTER COLUMN "CURRENCYFACTOR" NOT NULL;

ALTER TABLE CURRENCYRATE ADD COLUMN RATEb DECIMAL(20,8) DEFAULT 1;
UPDATE CURRENCYRATE SET RATEb=RATE;
ALTER TABLE CURRENCYRATE DROP COLUMN RATE;
RENAME COLUMN CURRENCYRATE.RATEb TO RATE;

