

DROP INDEX "APP"."EVENTS_STOCK_ANAME_DATE_DEF_TYPE";
DROP INDEX "APP"."EVENTS_STOCK_ANAME_DATE_DEF";
DROP INDEX "APP"."EVENTS_ANAME_DATE";
DROP INDEX "APP"."EVENTS_ANAME";

----UI : cleanEventsForAnalysisNameAndStock  EVENTS_STOCK_ANAME_DATE_DEF
CREATE INDEX "APP"."EVENTS_STOCK_ANAME_DATE_DEF" ON "APP"."EVENTS" ("ANALYSENAME", "SYMBOL", "ISIN", "DATE", "EVENTDEF");

----UI : cleanEventsForIndicators : EVENTS_ANAME_DATE_DEF
CREATE INDEX "APP"."EVENTS_ANAME_DATE_DEF" ON "APP"."EVENTS" ("ANALYSENAME", "DATE", "EVENTDEF");

----UI : loadEventsByDate : EVENTS_ANAME_DATE_DEF_TYPE
--Ignored

----UI : loadEventsByDate : EVENTS_STOCK_ANAME_DATE_DEF_TYPE
CREATE INDEX "APP"."EVENTS_STOCK_ANAME_DATE_DEF_TYPE" ON "APP"."EVENTS" ("ANALYSENAME", "SYMBOL", "ISIN", "DATE", "EVENTDEF", "EVENTTYPE");
