alter table SHARES add column CURRENCYFACTOR DECIMAL(9,2) not null DEFAULT 1;
alter table SHARES add column CURRENCY VARCHAR(32);


update SHARES set CURRENCY='GBP' where MARKETLISTPROVIDER='LSE';
update SHARES set CURRENCY='EUR' where MARKETLISTPROVIDER='EURONEXT' or MARKETLISTPROVIDER='PARIS';
update SHARES set CURRENCY='USD' where MARKETLISTPROVIDER='NASDAQ' or  MARKETLISTPROVIDER='NYSE' or MARKETLISTPROVIDER='AMEX';
update SHARES set CURRENCY='CAD' where MARKETLISTPROVIDER='TSX';
update SHARES set CURRENCY='INR' where MARKETLISTPROVIDER='BSE';
update SHARES set CURRENCY='AUD' where MARKETLISTPROVIDER='ASX';
update SHARES set CURRENCY='NAN' where MARKETLISTPROVIDER='UNKNOWN';

alter table SHARES alter column "CURRENCY" not null; -- derby
alter table SHARES CHANGE CURRENCY CURRENCY VARCHAR(32) NOT NULL; --my sql
--alter table SHARES CHANGE CURRENCYFACTOR CURRENCYFACTOR  DECIMAL(9,2) NOT NULL DEFAULT 1;


update SHARES set CURRENCYFACTOR=100 where MARKETLISTPROVIDER='LSE';
update SHARES set CURRENCYFACTOR=1 where MARKETLISTPROVIDER='LSE' and CATEGORY ='TRACKERS';


