--DONE
alter table TREND_SUPPLEMENT add column "YAHOOFORWARDPE" NUMERIC(19,2) DEFAULT 0;
alter table TREND_SUPPLEMENT add column "YAHOOEPSGROWTH" NUMERIC(19,2) DEFAULT 0;

-- "REUTERSFORWARDPE" NUMERIC(19,2), "REUTERSEPSGROWTH" NUMERIC(19,2), "REUTERSPE" NUMERIC(19,2), "REUTERSPAYOUTRATIO" NUMERIC(19,2));
alter table TREND_SUPPLEMENT add column "REUTERSFORWARDPE" NUMERIC(19,2) DEFAULT 0;
alter table TREND_SUPPLEMENT add column "REUTERSEPSGROWTH" NUMERIC(19,2) DEFAULT 0;
alter table TREND_SUPPLEMENT add column "REUTERSPE" NUMERIC(19,2) DEFAULT 0;
alter table TREND_SUPPLEMENT add column "REUTERSPAYOUTRATIO" NUMERIC(19,2) DEFAULT 0;

alter table TREND_SUPPLEMENT drop column "REUTERSEPSGROWTH";
alter table TREND_SUPPLEMENT drop column "REUTERSFORWARDPE";
alter table TREND_SUPPLEMENT add column "REUTERSLTGROWTH" NUMERIC(19,2) DEFAULT 0;

alter table TREND_SUPPLEMENT add column "BOURSOBNAGROWTH" NUMERIC(19,2) DEFAULT 0;
alter table TREND_SUPPLEMENT add column "BOURSOFORWARDPE" NUMERIC(19,2) DEFAULT 0;

alter table TREND_SUPPLEMENT add column "YAHOOEPS" NUMERIC(19,2) DEFAULT 0;
	