
--Unknown Market
insert into PORTFOLIO_NAME values ('UNKNOWN','ShareList',0.00,0.00,NULL,NULL,NULL);

select * from PERF_SUPPLEMENT left join PORTFOLIO on PERF_SUPPLEMENT.SYMBOL = PORTFOLIO.SYMBOL where PORTFOLIO.SYMBOL is NULL;
update PERF_SUPPLEMENT left join PORTFOLIO on PERF_SUPPLEMENT.SYMBOL = PORTFOLIO.SYMBOL  set PERF_SUPPLEMENT.NAME='UNKNOWN' where PORTFOLIO.SYMBOL is NULL;

insert into PORTFOLIO (SYMBOL, ISIN, NAME, QUANTITY, CASHIN, CASHOUT, MONITOR, BUYDATE, AVGBUYPRICE, TRANSACTIONCURRENCY, ACCOUNT) \
select PERF_SUPPLEMENT.SYMBOL, PERF_SUPPLEMENT.ISIN, PERF_SUPPLEMENT.NAME,  1.00000, 1.00, 0.00, 0, '1970-01-01',0.00,'NAN',NULL from PERF_SUPPLEMENT left join PORTFOLIO on PERF_SUPPLEMENT.SYMBOL = PORTFOLIO.SYMBOL where PORTFOLIO.SYMBOL is NULL\
GROUP BY PERF_SUPPLEMENT.SYMBOL, PERF_SUPPLEMENT.ISIN, PERF_SUPPLEMENT.NAME;

ALTER TABLE  PERF_SUPPLEMENT  ADD CONSTRAINT `FK_PERF_SUPPLEMENT_TO_PORTFOLIO` FOREIGN KEY (`SYMBOL`, `ISIN`, `NAME`) REFERENCES `PORTFOLIO` (`SYMBOL`, `ISIN`, `NAME`) ON DELETE NO ACTION ON UPDATE NO ACTION;

--NSE Indices
update PORTFOLIO_NAME set NAME='NSEINDICES,CNX100:NSE' where name='YAHOOINDICES,BSESN:BSE';


