ALTER TABLE USERS ADD COLUMN `REGISTRATIONDATE` DATE NOT NULL;
ALTER TABLE USERS ADD COLUMN `REGISTRATIONFORECAST` VARCHAR(32) DEFAULT NULL;
ALTER TABLE USERS ADD COLUMN `ISACTIVE` SMALLINT NOT NULL DEFAULT 1;
ALTER TABLE USERS ADD COLUMN `EVENTDEFINITION` varchar(100) DEFAULT NULL;
ALTER TABLE USERS ADD COLUMN `STOCKPARAMS` varchar(255) DEFAULT NULL;


ALTER TABLE USERS ADD CONSTRAINT FK_USER_TO_STOCK FOREIGN KEY (SYMBOL, ISIN) REFERENCES SHARES (SYMBOL, ISIN) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE PERF_SUPPLEMENT ADD COLUMN `EVENTDEFINITION` varchar(100) DEFAULT NULL;
update PERF_SUPPLEMENT set EVENTDEFINITION="NEURAL";
ALTER TABLE PERF_SUPPLEMENT CHANGE EVENTDEFINITION EVENTDEFINITION varchar(100) NOT NULL;
ALTER TABLE PERF_SUPPLEMENT ADD KEY PERF_SUPPLEMENT_LATEST (`LATEST`);
ALTER TABLE PERF_SUPPLEMENT DROP PRIMARY KEY;
ALTER TABLE PERF_SUPPLEMENT ADD CONSTRAINT PERF_SUPPLEMENT_PKEY PRIMARY KEY (SYMBOL, ISIN, NAME, PERFDATE, EVENTDEFINITION);


insert into USERS values ('guil@localhost.localdomain','ADSK','US0527691069','','2012-12-16','BEARISH',1,'NEURAL',NULL);
insert into USERS values ('guil@localhost.localdomain','BIIB','US09062X1037','','2012-12-16','BEARISH',1,'NEURAL',NULL);
insert into USERS values ('guil@localhost.localdomain','EXPE','US30212P1057','','2012-12-16','BEARISH',1,'NEURAL',NULL);

insert into USERS values ('guil@localhost.localdomain','GOOG','US38259P5089','','2012-12-01','BULLISH',1,'NEURAL',NULL);
