--done
alter table shares add column SECTOR_HINT VARCHAR(64);
alter table shares add column TRADING_MODE VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN';
alter table shares add column CAPITALISATION BIGINT NOT NULL DEFAULT 0;
alter table portfolio_name add column TYPE VARCHAR(32) DEFAULT 'default';
alter table portfolio_name add column "TOTALINAMOUNTEVER"  NUMERIC(19,2) DEFAULT 0;
alter table portfolio_name add column "TOTALOUTAMOUNTEVER" NUMERIC(19,2) DEFAULT 0;

update shares set SECTOR_HINT = '',TRADING_MODE = 'CONTINUOUS',CAPITALISATION = 0 where MARKETLISTPROVIDER <> 'EURONEXT';
-- + adminDB to update the Euronext market
-- + delete from events where symbol in (select symbol from shares where shares.trading_mode <> 'CONTINUOUS');
-- + delete from events where symbol in (select symbol from shares where shares.capitalisation < 150000000 and shares.capitalisation > 0 );
----select * from events where symbol in (select symbol from shares where shares.capitalisation < 150000000 and shares.capitalisation > 0 );
----select shares.isin, shares.symbol,shares.name, shares.MARKETLISTPROVIDER , shares.trading_mode
----from shares join events on shares.symbol = events.symbol and shares.isin = events.isin where shares.trading_mode <> 'CONTINUOUS';

CREATE TABLE "APP"."ALERTS_ALERTS" ("ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), "ALERTTYPE" VARCHAR(255), "OPTIONALMESSAGE" VARCHAR(255), "VALUE" NUMERIC(19,2), "ALERTS_ID" INTEGER);
CREATE TABLE "APP"."ALERTS" ("ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), "THRESHOLDTYPE" VARCHAR(255), "PORTFOLIOSHARE_ID" INTEGER);
drop index ISIN_INDEX;
drop index ISIN_DATE_INDEX;
ALTER TABLE "APP"."ALERTS" ADD CONSTRAINT "ALERTS_ID_PKEY" PRIMARY KEY ("ID");
ALTER TABLE "APP"."ALERTS_ALERTS" ADD CONSTRAINT "ALERTS_ALERTS_ID_PKEY" PRIMARY KEY ("ID");
ALTER TABLE "APP"."ALERTS_ALERTS" ADD CONSTRAINT "FK_ALERTSET" FOREIGN KEY ("ALERTS_ID") REFERENCES "APP"."ALERTS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."ALERTS" ADD CONSTRAINT "FK_AS_PORTFOLIO" FOREIGN KEY ("PORTFOLIOSHARE_ID") REFERENCES "APP"."PORTFOLIO" ("ID") ON DELETE CASCADE ON UPDATE NO ACTION;

alter table  ALERTS_ALERTS  add column ALERTTYPE VARCHAR(255);
alter table  ALERTS_ALERTS  add column VALUEB NUMERIC(19,2) DEFAULT 0;
update ALERTS_ALERTS set VALUEB = "VALUE";
alter table ALERTS_ALERTS drop column "VALUE";
alter table ALERTS_ALERTS add column "VALUE" NUMERIC(19,2) DEFAULT 0;
update ALERTS_ALERTS set "VALUE" = VALUEB;
alter table ALERTS_ALERTS drop column VALUEB;
