alter table USERS CHANGE STOCKPARAMS STOCKPARAMS VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE USERS drop PRIMARY KEY;
ALTER TABLE  USERS ADD  PRIMARY KEY (`EMAIL`,`SYMBOL`,`ISIN`,`NAME`,`EVENTDEFINITION`,`STOCKPARAMS`);

update USERS set STOCKPARAMS='FRFPR.NX FROG.NX FRBM.NX FRCG.NX FRFIN.NX FRIN.NX FRCS.NX FRHC.NX FRUT.NX FRTEL.NX FRTEC.NX' where EVENTDEFINITION='SECTOR';

update USERS set STOCKPARAMS='FRFPR.NX FROG.NX FRBM.NX FRCG.NX FRFIN.NX FRIN.NX FRCS.NX FRHC.NX FRUT.NX FRTEL.NX FRTEC.NX' where EVENTDEFINITION='SECTOR' and STOCKPARAMS='FRFPR.NX+FROG.NX+FRBM.NX+FRCG.NX+FRFIN.NX+FRIN.NX+FRCS.NX+FRHC.NX+FRUT.NX+FRTEL.NX+FRTEC.NX';


