
-- see dropSecondPassEvents.sh :
--export data
--recreate table
--re import data


delete from EVENTS where EVENTDEF=EVENTDEFEXTENSION;
delete from EVENTS where EVENTDEFID=0;
delete from EVENTS where EVENTDEFID=999;
UPDATE EVENTS set EVENTDEF=EVENTDEFEXTENSION;

-- see rebuildEventKeys.sh :
-- apply keys


ALTER TABLE ALERTONEVENT ADD CONSTRAINT `ALERTONEVENT_ID_PKEY` PRIMARY KEY (`SYMBOL`, `ISIN`, `NAME`, `EVENTINFOREFERENCE`, `MONITORLEVEL`);
ALTER TABLE ALERTONEVENT ADD CONSTRAINT `FK_ALERTONEVENT_TO_PORTFOLIO` FOREIGN KEY (`SYMBOL`, `ISIN`, `NAME`) REFERENCES `PORTFOLIO` (`SYMBOL`, `ISIN`, `NAME`) ON DELETE NO ACTION ON UPDATE NO ACTION;
