CREATE TABLE PERF_SUPPLEMENT (SYMBOL VARCHAR(20) NOT NULL, ISIN VARCHAR(20) NOT NULL, NAME VARCHAR(255) NOT NULL, PERFDATE DATE NOT NULL, EVENTDEFINITION varchar(100) NOT NULL, LATEST SMALLINT NOT NULL DEFAULT 1,TRENDFORECAST VARCHAR(32), ISREVERSAL SMALLINT NOT NULL DEFAULT 0, YEARLYPERF DECIMAL(10,4), MONTHLYPERF DECIMAL(10,4), WEEKLYPERF DECIMAL(10,4), DAILYPERF DECIMAL(10,4), \
KEY PERF_SUPPLEMENT_KEY (SYMBOL, ISIN, NAME, EVENTDEFINITION), \
CONSTRAINT PERF_SUPPLEMENT_PKEY PRIMARY KEY (SYMBOL, ISIN, NAME, PERFDATE, EVENTDEFINITION), \
CONSTRAINT FK_PERF_SUPPLEMENT_TO_PORTFOLIO FOREIGN KEY (SYMBOL, ISIN, NAME) REFERENCES PORTFOLIO (SYMBOL, ISIN, NAME) ON DELETE NO ACTION ON UPDATE NO ACTION) \
CHARACTER SET utf8;
	
--	insert into PERF_SUPPLEMENT values ('FTE.PA','FR0000133308','YAHOOINDICES,SBF250:EURONEXT','2012-12-06',1,'BEARISH',1,0.1,0.1,0.1,0.1);
--	insert into PERF_SUPPLEMENT values ('PAJ.PA','FR0010096354','YAHOOINDICES,SBF250:EURONEXT','2012-12-06',1,'BEARISH',0,0.1,0.1,0.1,0.1);
--	insert into PERF_SUPPLEMENT values ('MMM','MMM','YAHOOINDICES,DJI:NYSE','2012-12-06',1,'BULLISH',1,0.1,0.1,0.1,0.1);
--	insert into PERF_SUPPLEMENT values ('BAC','BAC','YAHOOINDICES,DJI:NYSE','2012-12-06',1,'BULLISH',0,0.1,0.1,0.1,0.1);	

CREATE INDEX PERF_SUPPLEMENT_LATEST ON PERF_SUPPLEMENT (LATEST);




CREATE TABLE "PERF_SUPPLEMENT" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "PERFDATE" DATE NOT NULL, "EVENTDEFINITION" varchar(100) NOT NULL, "LATEST" SMALLINT NOT NULL DEFAULT 1,"TRENDFORECAST" VARCHAR(32), "ISREVERSAL" SMALLINT NOT NULL DEFAULT 0, "YEARLYPERF" DECIMAL(10,4), "MONTHLYPERF" DECIMAL(10,4), "WEEKLYPERF" DECIMAL(10,4), "DAILYPERF" DECIMAL(10,4));
ALTER TABLE "APP"."PERF_SUPPLEMENT" ADD CONSTRAINT "PERF_SUPPLEMENT_KEY" PRIMARY KEY  ("SYMBOL", "ISIN", "NAME", "EVENTDEFINITION");
ALTER TABLE "APP"."PERF_SUPPLEMENT" ADD CONSTRAINT "FK_PERF_SUPPLEMENT_TO_PORTFOLIO" FOREIGN KEY ("SYMBOL", "ISIN", "NAME") REFERENCES "APP"."PORTFOLIO" ("SYMBOL", "ISIN", "NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE "USERS" ("EMAIL" varchar(100) NOT NULL,"SYMBOL" varchar(20) NOT NULL,   "ISIN" varchar(20) NOT NULL,   "NAME" varchar(255) NOT NULL,   "COMMENT" varchar(255),   "REGISTRATIONDATE" date NOT NULL,   "REGISTRATIONFORECAST" varchar(32) DEFAULT NULL,   "ISACTIVE" smallint NOT NULL DEFAULT 1,   "EVENTDEFINITION" varchar(100) DEFAULT NULL,   "STOCKPARAMS" varchar(255) DEFAULT NULL);
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_PKEY" PRIMARY KEY ("EMAIL","SYMBOL","ISIN","NAME");
ALTER TABLE "USERS" ADD CONSTRAINT "FK_USER_TO_PORTFOLIO" FOREIGN KEY ("SYMBOL", "ISIN", "NAME") REFERENCES "PORTFOLIO" ("SYMBOL", "ISIN", "NAME") ON DELETE NO ACTION;
