-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------
-- foreign
ALTER TABLE "APP"."PORTFOLIO" DROP CONSTRAINT "FK_PORTFOLIO_TO_PORTFOLIO_NAME";
ALTER TABLE "APP"."PORTFOLIO" DROP CONSTRAINT "FK_PORTFOLIO_TO_SHARES";
ALTER TABLE "APP"."TREND_SUPPLEMENT" DROP CONSTRAINT "FK_TREND_SUPPLEMENT_TO_SHARES";
ALTER TABLE "APP"."ALERTS" DROP CONSTRAINT "FK_ALERTS_TO_PORTFOLIO";

-- primary/unique
ALTER TABLE "APP"."PORTFOLIO" DROP CONSTRAINT "PORTFOLIO_PKEY";
ALTER TABLE "APP"."TREND_SUPPLEMENT" DROP CONSTRAINT "TREND_SUPPLEMENT_PKEY";
ALTER TABLE "APP"."PORTFOLIO_NAME" DROP CONSTRAINT "PORTFOLIO_NAME_PKEY";
ALTER TABLE "APP"."CURRENCYRATE" DROP CONSTRAINT "CURRENCYRATE_PKEY";
ALTER TABLE "APP"."EVENTS" DROP CONSTRAINT "EVENTS_PKEY";
ALTER TABLE "APP"."ALERTS" DROP CONSTRAINT "ALERTS_ID_PKEY";
ALTER TABLE "APP"."QUOTATIONS" DROP CONSTRAINT "QUOTATIONS_SYMBOL_ISIN_DATE";
ALTER TABLE "APP"."SHARES" DROP CONSTRAINT "SHARES_SYMBOL_ISIN";






