delete from events where eventdefid = 201;
alter table events add column "EVENTDEFEXTENSION" VARCHAR(100) NOT NULL DEFAULT '';
alter table events drop constraint "EVENTS_PKEY";
ALTER TABLE "APP"."EVENTS" ADD CONSTRAINT "EVENTS_PKEY" UNIQUE ("DATE", "EVENTDEFID", "EVENTDEFEXTENSION", "EVENTTYPE", "ANALYSENAME", "SYMBOL", "ISIN");
CREATE INDEX "APP"."EVENTS_ANAME_STOCK_IDDEF_DATE_TYPE" ON "APP"."EVENTS"  ("SYMBOL", "ISIN", "ANALYSENAME", "DATE", "EVENTDEFID", "EVENTTYPE");