-- ----------------------------------------------
-- DDL Statements for indexes
-- ----------------------------------------------


--EVENT table where closes 
--SYMBOL_FIELD ISIN_FIELD ANALYSE_NAME DATE_FIELD //Test only
--SYMBOL_FIELD ISIN_FIELD ANALYSE_NAME DATE_FIELD EVENTDEFID
--SYMBOL_FIELD ISIN_FIELD ANALYSE_NAME DATE_FIELD EVENTTYPE
--SYMBOL_FIELD ISIN_FIELD ANALYSE_NAME EVENTDEFID EVENTTYPE  order by DATE_FIELD
--ANALYSE_NAME DATE_FIELD EVENTDEFID
--ANALYSE_NAME DATE_FIELD
--ANALYSE_NAME 
-- KEY : "SYMBOL", "ISIN",  "ANALYSENAME", "DATE", "EVENTDEFID", "EVENTDEFEXTENSION"
CREATE INDEX "EVENTS_ANAME" on "EVENTS" ("ANALYSENAME");-- /minor usage?
CREATE INDEX "EVENTS_ANAME_DATE" on "EVENTS" ("ANALYSENAME","DATE"); -- /minor usage?
CREATE INDEX "EVENTS_ANAME_DATE_ID" on "EVENTS" ("ANALYSENAME","DATE","EVENTDEFID"); -- /minor usage?
CREATE INDEX "EVENTS_STOCK_ANAME_DATE_TYPE_ID" on "EVENTS" ("SYMBOL","ISIN","ANALYSENAME","DATE","EVENTTYPE","EVENTDEFID");
CREATE INDEX "EVENTS_STOCK_ANAME_DATE_TYPE" on "EVENTS" ("SYMBOL","ISIN","ANALYSENAME","DATE","EVENTTYPE");
CREATE INDEX "EVENTS_STOCK_ANAME_DATE_ID" on "EVENTS" ("SYMBOL","ISIN","ANALYSENAME","DATE","EVENTDEFID");

--Other tables
CREATE INDEX "APP"."TS_STOCK_DATE" ON "APP"."TREND_SUPPLEMENT" ("SYMBOL", "ISIN", "TRENDDATE");
CREATE INDEX "APP"."SYMBOL_ISIN_INDEX" ON "APP"."QUOTATIONS" ("SYMBOL", "ISIN");
CREATE INDEX "APP"."SHARES_SYMBOL" ON "APP"."SHARES" ("SYMBOL");