-- ----------------------------------------------
-- DDL Statements for indexes
-- ----------------------------------------------


--EVENT table where closes 
--SYMBOL_FIELD ISIN_FIELD ANALYSE_NAME DATE_FIELD //Test only
--SYMBOL_FIELD ISIN_FIELD ANALYSE_NAME DATE_FIELD EVENTDEFID
--SYMBOL_FIELD ISIN_FIELD ANALYSE_NAME DATE_FIELD EVENTTYPE
--SYMBOL_FIELD ISIN_FIELD ANALYSE_NAME EVENTDEFID EVENTTYPE  order by DATE_FIELD
--ANALYSE_NAME DATE_FIELD EVENTDEFID
--ANALYSE_NAME DATE_FIELD
--ANALYSE_NAME 
-- KEY : "SYMBOL", "ISIN",  "ANALYSENAME", "DATE", "EVENTDEFID", "EVENTDEFEXTENSION"

--CREATE INDEX "APP"."EVENTS_STOCK_ANAME_DATE" ON "APP"."EVENTS" ("SYMBOL", "ISIN", "ANALYSENAME", "DATE"); //Test only
CREATE INDEX "APP"."EVENTS_STOCK_ANAME_DATE_ID" ON "APP"."EVENTS" ("SYMBOL", "ISIN", "ANALYSENAME", "DATE", "EVENTDEFID");
CREATE INDEX "APP"."EVENTS_STOCK_ANAME_DATE_TYPE" ON "APP"."EVENTS" ("SYMBOL", "ISIN", "ANALYSENAME", "DATE", "EVENTTYPE");
CREATE INDEX "APP"."EVENTS_STOCK_ANAME_TYPE_ID" ON "APP"."EVENTS" ("SYMBOL", "ISIN", "ANALYSENAME", "EVENTTYPE", "EVENTDEFID");
CREATE INDEX "APP"."EVENTS_ANAME_DATE_ID" ON "APP"."EVENTS" ("ANALYSENAME", "DATE", "EVENTDEFID");
CREATE INDEX "APP"."EVENTS_ANAME_DATE" ON "APP"."EVENTS" ("ANALYSENAME", "DATE");
CREATE INDEX "APP"."EVENTS_ANAME" ON "APP"."EVENTS" ("ANALYSENAME");


--Other tables
CREATE INDEX "APP"."TS_STOCK_DATE" ON "APP"."TREND_SUPPLEMENT" ("SYMBOL", "ISIN", "TRENDDATE");
CREATE INDEX "APP"."SYMBOL_ISIN_INDEX" ON "APP"."QUOTATIONS" ("SYMBOL", "ISIN");
CREATE INDEX "APP"."SHARES_SYMBOL" ON "APP"."SHARES" ("SYMBOL");