--drop
ALTER TABLE EVENTS DROP INDEX `EVENTS_ANAME`;
ALTER TABLE  EVENTS DROP INDEX `EVENTS_ANAME_DATE`;
ALTER TABLE  EVENTS DROP INDEX `EVENTS_ANAME_DATE_ID`;
ALTER TABLE  EVENTS DROP INDEX `EVENTS_STOCK_ANAME_TYPE_ID`;
ALTER TABLE  EVENTS DROP INDEX `EVENTS_STOCK_ANAME_DATE_TYPE_ID`;
ALTER TABLE  EVENTS DROP INDEX `EVENTS_STOCK_ANAME_DATE_TYPE`;
ALTER TABLE  EVENTS DROP INDEX `EVENTS_STOCK_ANAME_DATE_ID`;

ALTER TABLE PERF_SUPPLEMENT DROP INDEX `PERF_SUPPLEMENT_KEY`;
ALTER TABLE PERF_SUPPLEMENT DROP INDEX `PERF_SUPPLEMENT_LATEST`; -- <=

ALTER TABLE QUOTATIONS DROP INDEX `SYMBOL_ISIN_INDEX`;

ALTER TABLE SHARES DROP INDEX `SHARES_SYMBOL`;



--alter
----ALTER TABLE EVENTS  ADD PRIMARY KEY  (`SYMBOL`,`ISIN`,`ANALYSENAME`,`DATE`,`EVENTDEFID`,`EVENTDEFEXTENSION`);
--ALTER TABLE EVENTS  ADD INDEX `EVENTS_ANAME` (`ANALYSENAME`);-- /minor usage?
--ALTER TABLE EVENTS  ADD INDEX `EVENTS_ANAME_DATE` (`ANALYSENAME`,`DATE`); -- /minor usage?
--ALTER TABLE EVENTS  ADD INDEX `EVENTS_ANAME_DATE_ID` (`ANALYSENAME`,`DATE`,`EVENTDEFID`); -- /minor usage?
--ALTER TABLE EVENTS  ADD INDEX `EVENTS_STOCK_ANAME_DATE_TYPE_ID` (`SYMBOL`,`ISIN`,`ANALYSENAME`,`DATE`,`EVENTTYPE`,`EVENTDEFID`); --
--ALTER TABLE EVENTS  ADD INDEX `EVENTS_STOCK_ANAME_DATE_TYPE` (`SYMBOL`,`ISIN`,`ANALYSENAME`,`DATE`,`EVENTTYPE`);--
--ALTER TABLE EVENTS  ADD INDEX `EVENTS_STOCK_ANAME_DATE_ID` (`SYMBOL`,`ISIN`,`ANALYSENAME`,`DATE`,`EVENTDEFID`);--
ALTER TABLE EVENTS  ADD INDEX `EVENTS_ANAME` (`ANALYSENAME`);
ALTER TABLE EVENTS  ADD INDEX `EVENTS_ANAME_DATE` (`ANALYSENAME`,`DATE`);
ALTER TABLE EVENTS  ADD INDEX `EVENTS_STOCK_ANAME_DATE_DEF` (`ANALYSENAME`,`SYMBOL`,`ISIN`,`DATE`,`EVENTDEF`);
ALTER TABLE EVENTS  ADD INDEX `EVENTS_STOCK_ANAME_DATE_DEF_TYPE` (`ANALYSENAME`,`SYMBOL`,`ISIN`,`DATE`,`EVENTDEF`,`EVENTTYPE`);
--ALTER TABLE EVENTS  ADD INDEX `EVENTS_TMP` (`SYMBOL`,`ISIN`,`DATE`);

ALTER TABLE PERF_SUPPLEMENT ADD INDEX  `PERF_SUPPLEMENT_KEY` (`SYMBOL`,`ISIN`,`NAME`, `EVENTDEFINITION`);--
ALTER TABLE PERF_SUPPLEMENT ADD INDEX  PERF_SUPPLEMENT_LATEST (LATEST);

ALTER TABLE QUOTATIONS ADD INDEX `SYMBOL_ISIN_INDEX` (`SYMBOL`,`ISIN`);

ALTER TABLE SHARES ADD INDEX `SHARES_SYMBOL` (`SYMBOL`);


