delete from QUOTATIONS where SYMBOL = 'SAB.L';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'SAB.L';
delete from QUOTATIONS where SYMBOL = 'HDFC.BO';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'HDFC.BO';
delete from QUOTATIONS where SYMBOL = 'CRH.L';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'CRH.L';
delete from QUOTATIONS where SYMBOL = 'IDFC.BO';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'IDFC.BO';
delete from QUOTATIONS where SYMBOL = 'BA.L';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'BA.L';
delete from QUOTATIONS where SYMBOL = 'RSA.L';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'RSA.L';
delete from QUOTATIONS where SYMBOL = 'IMI.L';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'IMI.L';
delete from QUOTATIONS where SYMBOL = 'TLW.L';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'TLW.L';
delete from QUOTATIONS where SYMBOL = 'FR.PA';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'FR.PA';
delete from QUOTATIONS where SYMBOL = 'CPG.L';
update SHARES set LASTQUOTE='1970-01-01' where SYMBOL = 'CPG.L';