connect 'jdbc:derby:TATA/derby/piggymarketsqueak';

CREATE TABLE "APP"."EVENTS_TMP" ("DATE" TIMESTAMP NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "EVENTDEF" CHAR(100), "EVENTTYPE" CHAR(1) NOT NULL, "ACCURACY" SMALLINT, "EVENTDEFID" SMALLINT NOT NULL, "EVENTDEFEXTENSION" VARCHAR(100) NOT NULL DEFAULT '', "ANALYSENAME" VARCHAR(256) NOT NULL DEFAULT 'AutoPortfolio', "MESSAGE" LONG VARCHAR);
insert into EVENTS_TMP select * from events where date > 'TOTO';

drop table EVENTS;
CREATE TABLE "APP"."EVENTS" ("DATE" TIMESTAMP NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "EVENTDEF" CHAR(100), "EVENTTYPE" CHAR(1) NOT NULL, "ACCURACY" SMALLINT, "EVENTDEFID" SMALLINT NOT NULL, "EVENTDEFEXTENSION" VARCHAR(100) NOT NULL DEFAULT '', "ANALYSENAME" VARCHAR(256) NOT NULL DEFAULT 'AutoPortfolio', "MESSAGE" LONG VARCHAR);
insert into EVENTS select * from EVENTS_TMP;
drop table EVENTS_TMP;
	
ALTER TABLE "APP"."EVENTS" ADD CONSTRAINT "EVENTS_PKEY" UNIQUE ("DATE", "EVENTDEFID", "EVENTDEFEXTENSION", "EVENTTYPE", "ANALYSENAME", "SYMBOL", "ISIN");
CREATE INDEX "APP"."EVENTS_ANALYSENAME_INDEX" ON "APP"."EVENTS" ("ANALYSENAME");
--CREATE INDEX "APP"."EVENTS_ANALYSENAME_DATE" ON "APP"."EVENTS" ("ANALYSENAME", "DATE", "EVENTDEFID"); 
--CREATE INDEX "APP"."EVENTS_ANAME_STOCK_IDDEF_TYPE" ON "APP"."EVENTS" ("SYMBOL", "ISIN", "ANALYSENAME", "EVENTTYPE", "EVENTDEFID"); 
CREATE INDEX "APP"."EVENTS_ANAME_STOCK_IDDEF_DATE_TYPE" ON "APP"."EVENTS"  ("SYMBOL", "ISIN", "ANALYSENAME", "DATE", "EVENTDEFID", "EVENTTYPE");
CREATE INDEX "APP"."EVENTS_ANAME_STOCK_ID_DATE_TYPE" ON "APP"."EVENTS" ("SYMBOL", "ISIN", "ANALYSENAME", "DATE", "EVENTTYPE");  
