-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------
-- primary/unique
ALTER TABLE "APP"."PORTFOLIO" ADD CONSTRAINT "PORTFOLIO_PKEY" PRIMARY KEY ("SYMBOL", "ISIN", "NAME");
ALTER TABLE "APP"."TREND_SUPPLEMENT" ADD CONSTRAINT "TREND_SUPPLEMENT_PKEY" UNIQUE ("TRENDDATE", "SYMBOL", "ISIN");
ALTER TABLE "APP"."PORTFOLIO_NAME" ADD CONSTRAINT "PORTFOLIO_NAME_PKEY" PRIMARY KEY ("NAME");
ALTER TABLE "APP"."CURRENCYRATE" ADD CONSTRAINT "CURRENCYRATE_PKEY" PRIMARY KEY ("FROMCURRENCY", "TOCURRENCY", "DATE");
ALTER TABLE "APP"."EVENTS" ADD CONSTRAINT "EVENTS_PKEY" UNIQUE ( "SYMBOL", "ISIN",  "ANALYSENAME", "DATE", "EVENTDEFID", "EVENTDEFEXTENSION");
ALTER TABLE "APP"."QUOTATIONS" ADD CONSTRAINT "QUOTATIONS_SYMBOL_ISIN_DATE" PRIMARY KEY ("SYMBOL", "ISIN", "DATE");
ALTER TABLE "APP"."ALERTS" ADD CONSTRAINT "ALERTS_ID_PKEY" PRIMARY KEY ("SYMBOL", "ISIN", "NAME", "THRESHOLDTYPE", "ALERTTYPE");
ALTER TABLE "APP"."SHARES" ADD CONSTRAINT "SHARES_SYMBOL_ISIN" UNIQUE ("SYMBOL", "ISIN");

-- foreign
ALTER TABLE "APP"."PORTFOLIO" ADD CONSTRAINT "FK_PORTFOLIO_TO_PORTFOLIO_NAME" FOREIGN KEY ("NAME") REFERENCES "APP"."PORTFOLIO_NAME" ("NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."PORTFOLIO" ADD CONSTRAINT "FK_PORTFOLIO_TO_SHARES" FOREIGN KEY ("SYMBOL", "ISIN") REFERENCES "APP"."SHARES" ("SYMBOL", "ISIN") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."TREND_SUPPLEMENT" ADD CONSTRAINT "FK_TREND_SUPPLEMENT_TO_SHARES" FOREIGN KEY ("SYMBOL", "ISIN") REFERENCES "APP"."SHARES" ("SYMBOL", "ISIN") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "APP"."ALERTS" ADD CONSTRAINT "FK_ALERTS_TO_PORTFOLIO" FOREIGN KEY ("SYMBOL", "ISIN", "NAME") REFERENCES "APP"."PORTFOLIO" ("SYMBOL", "ISIN", "NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

