-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "APP"."TRANSACTIONS" ADD CONSTRAINT "TRANSACTIONS_PKEY" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PERF_SUPPLEMENT" ADD CONSTRAINT "PERF_SUPPLEMENT_PKEY" PRIMARY KEY ("SYMBOL", "ISIN", "NAME", "PERFDATE", "EVENTDEFINITION");

ALTER TABLE "APP"."PORTFOLIO_NAME" ADD CONSTRAINT "PORTFOLIO_NAME_PKEY" PRIMARY KEY ("NAME");

ALTER TABLE "APP"."SHARES" ADD CONSTRAINT "SHARES_PKEY" PRIMARY KEY ("SYMBOL", "ISIN");

ALTER TABLE "APP"."QUOTATIONS" ADD CONSTRAINT "QUOTATIONS_PKEY" PRIMARY KEY ("SYMBOL", "ISIN", "DATE", "ORIGIN");

ALTER TABLE "APP"."ALERTS" ADD CONSTRAINT "ALERTS_PKEY" PRIMARY KEY ("SYMBOL", "ISIN", "NAME", "THRESHOLDTYPE", "ALERTTYPE");

ALTER TABLE "APP"."EVENTSCACHE" ADD CONSTRAINT "EVENTSCACHE_PKEY" PRIMARY KEY ("SYMBOL", "ISIN", "ANALYSENAME", "DATE", "EVENTDEF");

ALTER TABLE "APP"."TUNEDCONF" ADD CONSTRAINT "TUNEDCONF_PKEY" PRIMARY KEY ("SYMBOL", "ISIN", "CONFIGFILE", "EVENTDEFINITION");

ALTER TABLE "APP"."EVENTS" ADD CONSTRAINT "EVENTS_PKEY" PRIMARY KEY ("ANALYSENAME", "SYMBOL", "ISIN", "DATE", "EVENTDEF", "EVENTDEFEXTENSION");

ALTER TABLE "APP"."CURRENCYRATE" ADD CONSTRAINT "CURRENCYRATE_PKEY" PRIMARY KEY ("FROMCURRENCY", "TOCURRENCY", "DATE");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "USERS_PKEY" PRIMARY KEY ("EMAIL", "SYMBOL", "ISIN", "NAME", "EVENTDEFINITION", "STOCKPARAMS");

ALTER TABLE "APP"."PORTFOLIO" ADD CONSTRAINT "PORTFOLIO_PKEY" PRIMARY KEY ("SYMBOL", "ISIN", "NAME");

-- foreign
ALTER TABLE "APP"."PORTFOLIO" ADD CONSTRAINT "FK_PORTFOLIO_TO_PORTFOLIO_NAME" FOREIGN KEY ("NAME") REFERENCES "APP"."PORTFOLIO_NAME" ("NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PORTFOLIO" ADD CONSTRAINT "FK_PORTFOLIO_TO_SHARES" FOREIGN KEY ("SYMBOL", "ISIN") REFERENCES "APP"."SHARES" ("SYMBOL", "ISIN") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PERF_SUPPLEMENT" ADD CONSTRAINT "FK_PERF_SUPPLEMENT_TO_PORTFOLIO" FOREIGN KEY ("SYMBOL", "ISIN", "NAME") REFERENCES "APP"."PORTFOLIO" ("SYMBOL", "ISIN", "NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ALERTONEVENT" ADD CONSTRAINT "FK_ALERTONEVENT_TO_PORTFOLIO" FOREIGN KEY ("SYMBOL", "ISIN", "NAME") REFERENCES "APP"."PORTFOLIO" ("SYMBOL", "ISIN", "NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ALERTS" ADD CONSTRAINT "FK_ALERTS_TO_PORTFOLIO" FOREIGN KEY ("SYMBOL", "ISIN", "NAME") REFERENCES "APP"."PORTFOLIO" ("SYMBOL", "ISIN", "NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "FK_USER_TO_PORTFOLIO" FOREIGN KEY ("SYMBOL", "ISIN", "NAME") REFERENCES "APP"."PORTFOLIO" ("SYMBOL", "ISIN", "NAME") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TUNEDCONF" ADD CONSTRAINT "FK_TUNEDCONF_TO_SHARES" FOREIGN KEY ("SYMBOL", "ISIN") REFERENCES "APP"."SHARES" ("SYMBOL", "ISIN") ON DELETE NO ACTION ON UPDATE NO ACTION;
