DROP TABLE IF EXISTS `EVENTS`;

CREATE TABLE `EVENTS` (\
  `DATE` DATETIME NOT NULL,\
  `SYMBOL` varchar(20) NOT NULL,\
  `ISIN` varchar(20) NOT NULL,\
  `EVENTDEF` VARCHAR(100) NOT NULL,\
  `EVENTTYPE` VARCHAR(1) NOT NULL,\
  `ACCURACY` smallint(6) DEFAULT NULL,\
  `EVENTDEFID` smallint(6) NOT NULL,\
  `EVENTDEFEXTENSION` varchar(100) NOT NULL DEFAULT '',\
  `ANALYSENAME` varchar(256) NOT NULL DEFAULT 'AutoPortfolio',\
  `MESSAGE` mediumtext) ENGINE=InnoDB DEFAULT CHARSET=latin1;
  
 
