DROP TABLE IF EXISTS `EVENTS`;

CREATE TABLE `EVENTS` (\
  `DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\
  `SYMBOL` varchar(20) NOT NULL,\
  `ISIN` varchar(20) NOT NULL,\
  `EVENTDEF` char(100) DEFAULT NULL,\
  `EVENTTYPE` char(1) NOT NULL,\
  `ACCURACY` smallint(6) DEFAULT NULL,\
  `EVENTDEFID` smallint(6) NOT NULL,\
  `EVENTDEFEXTENSION` varchar(100) NOT NULL DEFAULT '',\
  `ANALYSENAME` varchar(256) NOT NULL DEFAULT 'AutoPortfolio',\
  `MESSAGE` mediumtext) ENGINE=InnoDB;
  
 
