--TODO change indices (see INDEXES.sql)

drop table events;

CREATE TABLE "APP"."EVENTS" ("DATE" TIMESTAMP NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "EVENTDEF" VARCHAR(100) NOT NULL, "EVENTTYPE" VARCHAR(1) NOT NULL, "ACCURACY" SMALLINT, "EVENTDEFID" SMALLINT NOT NULL, "EVENTDEFEXTENSION" VARCHAR(100) NOT NULL DEFAULT '', "ANALYSENAME" VARCHAR(256) NOT NULL DEFAULT 'AutoPortfolio', "MESSAGE" LONG VARCHAR);

ALTER TABLE "APP"."EVENTS" ADD CONSTRAINT "EVENTS_PKEY" PRIMARY KEY ( "ANALYSENAME", "SYMBOL", "ISIN", "DATE", "EVENTDEF", "EVENTDEFEXTENSION");

CREATE INDEX "EVENTS_ANAME" on "EVENTS" ("ANALYSENAME");
CREATE INDEX "EVENTS_ANAME_DATE" on "EVENTS" ("ANALYSENAME","DATE");
CREATE INDEX "EVENTS_STOCK_ANAME_DATE_DEF" on "EVENTS" ("ANALYSENAME","SYMBOL","ISIN","DATE","EVENTDEF");
CREATE INDEX "EVENTS_STOCK_ANAME_DATE_DEF_TYPE" on "EVENTS" ("ANALYSENAME","SYMBOL","ISIN","DATE","EVENTDEF","EVENTTYPE");