
--TODO change indices (see INDEXES.sql)

ALTER TABLE EVENTS  ADD PRIMARY KEY ( `ANALYSENAME`, `SYMBOL`, `ISIN`, `DATE`, `EVENTDEF`, `EVENTDEFEXTENSION`);

ALTER TABLE EVENTS  ADD INDEX `EVENTS_ANAME` (`ANALYSENAME`);
ALTER TABLE EVENTS  ADD INDEX `EVENTS_ANAME_DATE` (`ANALYSENAME`,`DATE`);
ALTER TABLE EVENTS  ADD INDEX `EVENTS_STOCK_ANAME_DATE_DEF` (`ANALYSENAME`,`SYMBOL`,`ISIN`,`DATE`,`EVENTDEF`);
ALTER TABLE EVENTS  ADD INDEX `EVENTS_STOCK_ANAME_DATE_DEF_TYPE` (`ANALYSENAME`,`SYMBOL`,`ISIN`,`DATE`,`EVENTDEF`,`EVENTTYPE`);
