-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "APP"."TRANSACTIONS" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "EXTERNALACCOUNT" VARCHAR(255), "DATE" DATE NOT NULL, "QUANTITY" DECIMAL(19,0), "PRICE" DECIMAL(20,0), "CURRENCY" CHAR(3) NOT NULL, "PORTFOLIO" VARCHAR(255), "ID" BIGINT NOT NULL);

CREATE TABLE "APP"."CURRENCYRATE" ("FROMCURRENCY" INTEGER NOT NULL, "TOCURRENCY" INTEGER NOT NULL, "DATE" DATE NOT NULL, "RATE" DECIMAL(20,0));

CREATE TABLE "APP"."DBCOPYTEST" ("WIND" CHAR(10));

CREATE TABLE "APP"."WEATHER" ("DATE" DATE NOT NULL, "MAXTEMP" SMALLINT, "AVGTEMP" SMALLINT, "MINTEMP" SMALLINT, "PRECIPITATION" DECIMAL(19,0), "WIND" SMALLINT);

CREATE TABLE "APP"."QUOTATIONS" ("DATE" DATE NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "CURRENCY" CHAR(3), "VOLUME" BIGINT, "OPENVALUE" DECIMAL(20,0), "CLOSEVALUE" DECIMAL(20,0), "HIGH" DECIMAL(20,0), "LOW" DECIMAL(20,0), "ORIGIN" SMALLINT NOT NULL);

CREATE TABLE "APP"."TUNEDCONF" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "CONFIGFILE" VARCHAR(50) NOT NULL, "LASTCALCULATIONSTART" DATE NOT NULL, "LASTCALCULATEDEVENT" DATE, "LASTCALCULATIONEND" DATE NOT NULL, "EVENTDEFINITION" VARCHAR(100) NOT NULL, "DIRTY" SMALLINT);

CREATE TABLE "APP"."EVENTS" ("DATE" TIMESTAMP NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "EVENTDEF" VARCHAR(100) NOT NULL, "EVENTTYPE" VARCHAR(1) NOT NULL, "ACCURACY" SMALLINT, "EVENTDEFID" SMALLINT NOT NULL, "EVENTDEFEXTENSION" VARCHAR(100) NOT NULL, "ANALYSENAME" VARCHAR(256) NOT NULL, "MESSAGE" CLOB(16777215));

CREATE TABLE "APP"."EVENTSCACHE" ("DATE" TIMESTAMP NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "EVENTDEF" VARCHAR(100) NOT NULL, "EVENTTYPE" VARCHAR(1) NOT NULL, "ACCURACY" SMALLINT, "EVENTDEFID" SMALLINT NOT NULL, "EVENTDEFEXTENSION" VARCHAR(100) NOT NULL, "ANALYSENAME" VARCHAR(256) NOT NULL, "MESSAGE" CLOB(16777215));

CREATE TABLE "APP"."PORTFOLIO" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "QUANTITY" DECIMAL(19,0), "MONITOR" SMALLINT NOT NULL, "BUYDATE" DATE, "TRANSACTIONCURRENCY" CHAR(3) NOT NULL, "EXTERNALACCOUNT" VARCHAR(255), "AVGBUYPRICE" DECIMAL(20,0), "CASHIN" DECIMAL(20,0), "CASHOUT" DECIMAL(20,0));

CREATE TABLE "APP"."SHARES" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(100) NOT NULL, "LASTQUOTE" DATE NOT NULL, "REMOVABLE" SMALLINT NOT NULL, "QUOTATIONPROVIDER" VARCHAR(32), "MARKETLISTPROVIDER" VARCHAR(32), "CATEGORY" VARCHAR(255), "SECTOR_HINT" VARCHAR(64), "TRADING_MODE" VARCHAR(64) NOT NULL, "CAPITALISATION" BIGINT NOT NULL, "CURRENCYFACTOR" DECIMAL(9,0) NOT NULL, "CURRENCY" VARCHAR(32) NOT NULL);

CREATE TABLE "APP"."USERS" ("EMAIL" VARCHAR(100) NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "COMMENT" CLOB(16777215), "REGISTRATIONDATE" DATE NOT NULL, "REGISTRATIONFORECAST" VARCHAR(32), "ISACTIVE" SMALLINT NOT NULL, "EVENTDEFINITION" VARCHAR(100) NOT NULL, "STOCKPARAMS" VARCHAR(255) NOT NULL);

CREATE TABLE "APP"."TREND_SUPPLEMENT" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "BOURSOMEANRECOMMENDATIONS" DECIMAL(19,0), "BOURSOTARGETPRICE" DECIMAL(19,0), "YAHOOMEANRECOMMENDATIONS" DECIMAL(19,0), "YAHOOTARGETPRICE" DECIMAL(19,0), "DIVIDEND" DECIMAL(10,0), "REUTERSYIELD" DECIMAL(10,0), "YAHOOEPS" DECIMAL(19,0), "YAHOOESTEPS" DECIMAL(19,0), "REUTERSEPS" DECIMAL(19,0), "REUTERSESTEPS" DECIMAL(19,0), "REUTERSPAYOUTRATIO" DECIMAL(19,0), "BOURSOBNA" DECIMAL(19,0), "BOURSOESTBNA" DECIMAL(19,0), "TRENDDATE" DATE NOT NULL);

CREATE TABLE "APP"."ALERTONEVENT" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "EVENTINFOREFERENCE" VARCHAR(100) NOT NULL, "MONITORLEVEL" SMALLINT NOT NULL, "OPTIONALMESSAGE" CLOB(16777215));

CREATE TABLE "APP"."PORTFOLIO_NAME" ("NAME" VARCHAR(255) NOT NULL, "TYPE" VARCHAR(32), "BUYPONDERATIONRULE" BLOB(1073741823), "SELLPONDERATIONRULE" BLOB(1073741823), "PORTFOLIOCURRENCY" CHAR(3), "TOTALINAMOUNTEVER" DECIMAL(20,0), "TOTALOUTAMOUNTEVER" DECIMAL(20,0));

CREATE TABLE "APP"."PERF_SUPPLEMENT" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "PERFDATE" DATE NOT NULL, "LATEST" SMALLINT NOT NULL, "TRENDFORECAST" VARCHAR(32), "ISREVERSAL" SMALLINT NOT NULL, "YEARLYPERF" DECIMAL(10,0), "MONTHLYPERF" DECIMAL(10,0), "WEEKLYPERF" DECIMAL(10,0), "DAILYPERF" DECIMAL(10,0), "EVENTDEFINITION" VARCHAR(100) NOT NULL);

CREATE TABLE "APP"."ALERTS" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "ALERTTYPE" VARCHAR(255) NOT NULL, "THRESHOLDTYPE" VARCHAR(255) NOT NULL, "VALUE" DECIMAL(20,0) NOT NULL, "OPTIONALMESSAGE" CLOB(16777215));

