-- Timestamp: 2014-02-15 03:07:23.86
-- Source database is: /home/guil/Developpement/Quotes/premiummarkets
-- Connection URL is: jdbc:derby:/home/guil/Developpement/Quotes/premiummarkets
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "APP"."SHARES" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(100) NOT NULL, "LASTQUOTE" DATE NOT NULL, "REMOVABLE" SMALLINT NOT NULL DEFAULT 0, "QUOTATIONPROVIDER" VARCHAR(32), "MARKETLISTPROVIDER" VARCHAR(32), "CATEGORY" VARCHAR(255), "SECTOR_HINT" VARCHAR(64), "TRADING_MODE" VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN', "CAPITALISATION" BIGINT NOT NULL DEFAULT 0, "CURRENCYFACTOR" DECIMAL(9,2) NOT NULL DEFAULT 1, "CURRENCY" VARCHAR(32) NOT NULL);

CREATE TABLE "APP"."CURRENCYRATE" ("FROMCURRENCY" INTEGER NOT NULL, "TOCURRENCY" INTEGER NOT NULL, "DATE" DATE NOT NULL, "RATE" DECIMAL(20,8) DEFAULT 1);

CREATE TABLE "APP"."WEATHER" ("DATE" DATE NOT NULL, "MAXTEMP" SMALLINT, "AVGTEMP" SMALLINT, "MINTEMP" SMALLINT, "PRECIPITATION" NUMERIC(19,5), "WIND" SMALLINT);

CREATE TABLE "APP"."TUNEDCONF" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "CONFIGFILE" VARCHAR(50) NOT NULL, "LASTCALCULATIONSTART" DATE NOT NULL DEFAULT '1970-01-01', "LASTCALCULATIONEND" DATE NOT NULL DEFAULT '1970-01-01', "LASTCALCULATEDEVENT" DATE);

CREATE TABLE "APP"."USERS" ("EMAIL" VARCHAR(100) NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "COMMENT" VARCHAR(255), "REGISTRATIONDATE" DATE NOT NULL, "REGISTRATIONFORECAST" VARCHAR(32) DEFAULT NULL, "ISACTIVE" SMALLINT NOT NULL DEFAULT 1, "EVENTDEFINITION" VARCHAR(100) DEFAULT NULL, "STOCKPARAMS" VARCHAR(255) DEFAULT NULL);

CREATE TABLE "APP"."TRANSACTIONS" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "EXTERNALACCOUNT" VARCHAR(255), "DATE" DATE NOT NULL, "QUANTITY" NUMERIC(19,5), "PRICE" DECIMAL(20,4), "CURRENCY" CHAR(3) NOT NULL DEFAULT 'EUR', "PORTFOLIO" VARCHAR(255), "ID" BIGINT NOT NULL DEFAULT 0);

CREATE TABLE "APP"."ALERTS" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "ALERTTYPE" VARCHAR(255) NOT NULL, "THRESHOLDTYPE" VARCHAR(255) NOT NULL, "OPTIONALMESSAGE" LONG VARCHAR, "VALUE" DECIMAL(20,4) DEFAULT 0);

CREATE TABLE "APP"."QUOTATIONS" ("DATE" DATE NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "CURRENCY" CHAR(3), "VOLUME" BIGINT DEFAULT 0, "OPENVALUE" DECIMAL(20,4), "CLOSEVALUE" DECIMAL(20,4), "HIGH" DECIMAL(20,4), "LOW" DECIMAL(20,4), "ORIGIN" SMALLINT NOT NULL DEFAULT 0);

CREATE TABLE "APP"."PORTFOLIO" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "QUANTITY" NUMERIC(19,5), "CASHIN" NUMERIC(19,2), "CASHOUT" NUMERIC(19,2), "NAME" VARCHAR(255) NOT NULL, "MONITOR" SMALLINT NOT NULL DEFAULT 0, "BUYDATE" DATE DEFAULT '01/01/1970', "TRANSACTIONCURRENCY" CHAR(3) NOT NULL DEFAULT 'EUR', "EXTERNALACCOUNT" VARCHAR(255), "AVGBUYPRICE" DECIMAL(20,4) DEFAULT 0);

CREATE TABLE "APP"."TREND_SUPPLEMENT" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "BOURSOMEANRECOMMENDATIONS" NUMERIC(19,2), "BOURSOTARGETPRICE" NUMERIC(19,2), "YAHOOMEANRECOMMENDATIONS" NUMERIC(19,2), "YAHOOTARGETPRICE" NUMERIC(19,2), "DIVIDEND" DECIMAL(10,2), "REUTERSYIELD" DECIMAL(10,2), "YAHOOEPS" NUMERIC(19,2), "YAHOOESTEPS" NUMERIC(19,2), "REUTERSEPS" NUMERIC(19,2), "REUTERSESTEPS" NUMERIC(19,2), "REUTERSPAYOUTRATIO" NUMERIC(19,2), "BOURSOBNA" NUMERIC(19,2), "BOURSOESTBNA" NUMERIC(19,2), "TRENDDATE" DATE NOT NULL DEFAULT '1970-01-01');

CREATE TABLE "APP"."PERF_SUPPLEMENT" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "PERFDATE" DATE NOT NULL, "EVENTDEFINITION" VARCHAR(100) NOT NULL, "LATEST" SMALLINT NOT NULL DEFAULT 1, "TRENDFORECAST" VARCHAR(32), "ISREVERSAL" SMALLINT NOT NULL DEFAULT 0, "YEARLYPERF" DECIMAL(10,4), "MONTHLYPERF" DECIMAL(10,4), "WEEKLYPERF" DECIMAL(10,4), "DAILYPERF" DECIMAL(10,4));

CREATE TABLE "APP"."EVENTS" ("DATE" TIMESTAMP NOT NULL, "SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "EVENTDEF" VARCHAR(100) NOT NULL, "EVENTTYPE" VARCHAR(1) NOT NULL, "ACCURACY" SMALLINT, "EVENTDEFID" SMALLINT NOT NULL, "EVENTDEFEXTENSION" VARCHAR(100) NOT NULL DEFAULT '', "ANALYSENAME" VARCHAR(256) NOT NULL DEFAULT 'AutoPortfolio', "MESSAGE" LONG VARCHAR);

CREATE TABLE "APP"."ALERTONEVENT" ("SYMBOL" VARCHAR(20) NOT NULL, "ISIN" VARCHAR(20) NOT NULL, "NAME" VARCHAR(255) NOT NULL, "EVENTINFOREFERENCE" VARCHAR(100) NOT NULL, "MONITORLEVEL" SMALLINT NOT NULL DEFAULT 0, "OPTIONALMESSAGE" LONG VARCHAR);

CREATE TABLE "APP"."PORTFOLIO_NAME" ("NAME" VARCHAR(255) NOT NULL, "TYPE" VARCHAR(32) DEFAULT 'default', "TOTALINAMOUNTEVER" NUMERIC(19,2) DEFAULT 0, "TOTALOUTAMOUNTEVER" NUMERIC(19,2) DEFAULT 0, "BUYPONDERATIONRULE" BLOB(2147483647), "SELLPONDERATIONRULE" BLOB(2147483647), "PORTFOLIOCURRENCY" CHAR(3));
