CREATE TABLE "APP"."WEATHER" ("DATE" DATE NOT NULL, "MAXTEMP" SMALLINT, "AVGTEMP" SMALLINT, "MINTEMP" SMALLINT, "PRECIPITATION" NUMERIC(19,5), "WIND" SMALLINT);

ALTER TABLE "APP"."EVENTS" DROP CONSTRAINT "EVENTS_PKEY";
alter table events alter column "EVENTTYPE"  not null;
ALTER TABLE "APP"."EVENTS" ADD CONSTRAINT "EVENTS_PKEY" UNIQUE ("DATE", "EVENTDEFID", "EVENTTYPE", "ANALYSENAME", "SYMBOL", "ISIN");

alter table "APP"."ALERTS" alter column "THRESHOLDTYPE"  not null;
alter table "APP"."ALERTS" alter column "SYMBOL"  not null;
alter table "APP"."ALERTS" alter column "ISIN"  not null;
alter table "APP"."ALERTS" alter column "NAME"  not null;
ALTER TABLE "APP"."ALERTS" ADD CONSTRAINT "ALERTS_KEY" UNIQUE ("THRESHOLDTYPE", "SYMBOL", "ISIN", "NAME");

